apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "default"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.host }}

  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: {{ .Values.ingress.port }}

